fix: subprocess: include both stdout and stderr
Failed process may emit both stdout and stderr. Currently we
only propogate one (giving precedence to stdout), potentially
causing loss of data, e.g.:

Leons-MBP:snyk-docker-plugin leongold$ docker inspect foo:123
[] <--- stdout
Error: No such object: foo:123 <--- stderr

Refactor the project to return both in a single object, i.e
{stdout, stderr}